version: '3.7'
services:

  app:
    build: ./app
    volumes: ['./app:/app']
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    ports:
      - 5001:5001
    depends_on:
      - mongo

  mongo:
    image: 'mongo'
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    command: mongod --quiet --logpath /dev/null

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://username:password@mongo:27017/
